#!/usr/bin/env bash
# Regenerate ARCHITECTURE.md from per-directory README.md `purpose:` frontmatter.
# Idempotent. Runs in .githooks/pre-commit.

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

OUT="ARCHITECTURE.md"

extract_purpose() {
  local readme="$1"
  [ -f "$readme" ] || return 0
  awk '
    BEGIN { in_fm = 0; line = 0 }
    {
      line++
      if (line == 1 && $0 == "---") { in_fm = 1; next }
      if (in_fm && $0 == "---")     { exit }
      if (in_fm && match($0, /^purpose:[[:space:]]*/)) {
        val = substr($0, RLENGTH + 1)
        sub(/^["\047]/, "", val)
        sub(/["\047]$/, "", val)
        print val
        exit
      }
    }
  ' "$readme"
}

# Collect every ancestor directory of every tracked file.
dirs=$(
  git ls-files |
  while IFS= read -r f; do
    d=$(dirname "$f")
    while [ "$d" != "." ] && [ "$d" != "/" ] && [ -n "$d" ]; do
      printf '%s\n' "$d"
      d=$(dirname "$d")
    done
  done |
  sort -u
)

{
  echo "# Architecture Map"
  echo
  echo "_Auto-generated by \`scripts/build-arch-map.sh\` (runs in \`.githooks/pre-commit\`). To update an entry, edit the \`purpose:\` frontmatter in that directory's \`README.md\` and commit._"
  echo
  echo "| Path | Purpose |"
  echo "|------|---------|"

  while IFS= read -r d; do
    [ -z "$d" ] && continue
    case "$d" in
      .git|.git/*) continue ;;
    esac
    purpose=$(extract_purpose "$d/README.md")
    [ -z "$purpose" ] && purpose="_(no \`purpose:\` set in \`$d/README.md\`)_"
    printf "| \`%s/\` | %s |\n" "$d" "$purpose"
  done <<< "$dirs"
} > "$OUT.tmp"

mv "$OUT.tmp" "$OUT"
echo "build-arch-map: wrote $OUT"
